### ISSUE TITLE
SP agregarlos

### ISSUE THREAD

**Issue by orellana888** [orellana888/Sistema-SAAT#5]
Porfavor agg en tu bd PROCEDIMIENDO ALMACENADO PARA LOS 3 COLEGIOS:

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_REGISTRAR_APROBADO_CIMEQH`(IN EXPE VARCHAR(45),IN PROYECT VARCHAR(100), IN PROPI VARCHAR(50), IN CLAVE VARCHAR(100),IN DATO_AREA FLOAT, IN PRESUPUESTO FLOAT,IN ESTATUS VARCHAR(30) ,IN OBSERVACIONES VARCHAR(100), IN FECHA DATE)
BEGIN 
	INSERT INTO proyectoscimeqh(num_expediente,tipo_proyecto,propietario,clave_catastral,area,presupuesto,estatus,observaciones,fecha) 
    VALUES (EXPE,PROYECT,PROPI,CLAVE,DATO_AREA,PRESUPUESTO,ESTATUS,OBSERVACIONES,FECHA);
END

(agg, estatus)

**Comment by EdgardOrd** [comment]
Listo!!
